//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentsArchiving.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentId { get; set; }
        public string Subject { get; set; }
        public int DocumentTypeId { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public string SerialNumber { get; set; }
        public string Details { get; set; }
        public string Path { get; set; }
    
        public virtual DocumentType DocumentType { get; set; }
    }
}
